### ISSUE TITLE
Most-left and most-right columns in gallery are not clickable

### ISSUE THREAD

**Issue by anxolerd** [uaprom-summer-2015/Meowth#149]
## Description
It is impossible to click images which are in the most-left and most-right columns in gallery. It happens because `.border.borderleft` and `.border.borderright` divs overlay gallery images.

## STR
- run application
- if there are no images in the gallery upload them
- load main page
- scroll down to the gallery
- try to click on image which is in the most left or the most right column

## Expected result
Image preview is opened

## Actual result
I cannot click image because something is over that image

### Image I can click
![Developer mode](https://cloud.githubusercontent.com/assets/6533582/9364570/c5abdec2-46b5-11e5-995e-943043e614d2.png)

### Image in the most-left column
![Developer mode](https://cloud.githubusercontent.com/assets/6533582/9364645/239ef802-46b6-11e5-868c-cd67ec34c3a5.png)

**Comment by anxolerd** [comment]
@akhalyavka by the way there is no `hidden` value for `display` attribute. 
[RTFM](https://developer.mozilla.org/en-US/docs/Web/CSS/display)

However there is `hidden` value in `visibility` attribute
[RTFM](https://developer.mozilla.org/en-US/docs/Web/CSS/visibility)

**Comment by akhalyavka** [comment]
solved 
#152
