### ISSUE TITLE
Gallery is freaking dumb

### ISSUE THREAD

**Issue by Cybran111** [uaprom-summer-2015/Meowth#162]
Если поиграться мышкой, галерея:
1. Дёргается, если двигать мышку вверх-вниз
2. Скролл происходит, даже когда мышка слишком далеко от края (дальше, чем размер одного блока). Возможно, это связано с реализацией свайпа.

**Comment by anxolerd** [comment]
Від себе додам (сорі, що без скріншотів)
- На **IE 11** смикання галереї просто мегаепічне.
- На тому ж **IE 11** меі не вдалося змусити галерею скролитися. Вона лише смикалася

Можливо завтра спробую потестити ще **Edge**

**Comment by Cybran111** [comment]
Also, swipe on gallery isn't works.

**Comment by anxolerd** [comment]
See PR #177

**Comment by Cybran111** [comment]
Fixed.
