### ISSUE TITLE
Cannot attach file on Android's Firefox

### ISSUE THREAD

**Issue by Cybran111** [uaprom-summer-2015/Meowth#176]
**Problem**
The button doesn't starting any action to choose a file to attach, but triggers validation.

On Chrome all's OK.

![screenshot_2015-08-21-19-48-36](https://cloud.githubusercontent.com/assets/3594761/9413978/e9a3ba82-483d-11e5-90cd-b4bfa5d9b1d1.png)

**Comment by anxolerd** [comment]
Лажає у **firefox** узагалі, а не тільки на Android

**Comment by anxolerd** [comment]
Але, схоже, що це мій косяк.
Я просив Кирила зробити це кнопкою (ну це, кагбе, логічніше), тільки от кнопкою у вогнелисі, як виявилося, не працює =(
