### ISSUE TITLE
Cannot edit user details in admin

### ISSUE THREAD

**Issue by anxolerd** [uaprom-summer-2015/Meowth#180]
## Description
It is impossible to edit user after it was created without changing his login and email

## STR
1. start app
2. create a user via admin *(there are troubles with that too: see #179)*
3. Go to editing newly created user after it was created and corresponding entry was written to DB
4. Change last name (surname) of the user *(this is a real case -- assume this is a woman who changed her last name after marriage)* **Do not touch username or email**
5. Click save

## Expected result
User was successfully updated

## Actual result
Form considered invalid
![invalid form](https://cloud.githubusercontent.com/assets/6533582/9429407/c89e07ac-49d7-11e5-9041-a8ef69b6e4b4.png)

## Comments
This is due to `project.auth.validators.Exists` [implementation](https://github.com/uaprom-summer-2015/Meowth/blob/master/project/auth/validators.py#L33-L54).

**Comment by anxolerd** [comment]
This happens because corresponding form is created twice:

- First time it is created when user sends `GET` request. This time form is populated with object from database and `field.object_data` is set.
- Second time form is created when user sends `POST` request after making changes in form. This time no object passed to the form hence `field.object_data` is set to default field value. So it is totally different form and it does not contain `object_data` you passed there.

**Comment by akhalyavka** [comment]
Look #183

**Comment by Cybran111** [comment]
Fixed in #185
