### ISSUE TITLE
Pageblocks causing following elements to float on >=1024px

### ISSUE THREAD

**Issue by anxolerd** [uaprom-summer-2015/Meowth#188]
## Description
Because of `float: left;` [style](https://github.com/uaprom-summer-2015/Meowth/blob/master/project/static/src/css/pageblocks.styl#L44) latest pageblock causes following layout to float.

## Screenshot
![image](https://cloud.githubusercontent.com/assets/6533582/9453860/2b642878-4ac6-11e5-9ffe-b8efd0a3b90b.png)

## Suggestions
Wrap pageblocks into special container with the following style:
```styl
.container-pageblock:after
    clear both
    content ""
    display block
    font-size 0px
    height 0px
    width 0px
```

This will create an invisible cleaner for `container-pageblock` class.

**Comment by Cybran111** [comment]
Fixed.
